concord-consortium/lab

src/lab/common/controllers/data-set.js
src/lab/common/controllers/graph-controller.js

Changes summary:
- `lab-grapher` submodule is updated, there was a bug causing errors once dataset with null values was loaded.
- `DataSet#removeDataPoint` interface is more sane now - just set of properties to remove and index.
- When user is drawing points on the graph, only Y values are removed from dataset (@scytacki, @psndcsrv, X value is untouched, so authors can share X property). Previously there was a bug and only X value was removed.
- `GraphController` is making sure that correct point is removed when user is drawing on the graph (it looks for the exact combination of X and Y values, previously it wasn't ensured at all).
Tests:
1. You can checkout this branch, run local Lab server, open:
http://lab.concord.org/interactives-local.html#interactives/itsi/sensor/prediction-predictio …

Fix dataset remove datapoint and grapher

---

src/lab/common/controllers/div-controller.js
src/lab/common/controllers/interactive-metadata.js

You can see an example of this here:
http://lab.concord.org/branch/remote-div/interactives.html#interactives/basic-examples/remote-div-content.json
Here are the files making up that example:
https://github.com/concord-consortium/lab-interactives-site/commit/a25289b5cccd541afc5a6907b0dae8c54816225c
Besides checking the code, I'm curious what other people think about this approach. It allows us to add pretty much any html/javascript to the interactive.  So it will be easier to do more things. Some downsides and mitigations:
- if we had a authoring system that was vulnerable to cross site scripting, this would let users inject remote 'un-sandboxed' scripts. Mitigation: the authoring system could forbid using this.
- it is easy for authors to make interactives that break. Mitigation: use with …

allow authors to put div content in a separate file

---

src/lab/common/controllers/interactive-metadata.js
src/lab/common/controllers/radio-controller.js
src/sass/lab/_interactive-components.sass

This PR adds a new `style` option (`radio` or `toggle`) to the radio button component.
Its DOM structure has been slightly refactored, so now it's enough to add `toggle` class to the top level container and everything else is handled using CSS.

 Add toggle style to radio buttons

---

src/lab/common/layout/semantic-layout.js
src/sass/lab/_semantic-layout.sass

This PR adds two new properties to container definition:
* `border` - accepts typical CSS syntax (e.g. `1px solid gray`).
* `margin` - it's similar to existing `padding` option. Basically unless you add borders, it doesn't matter whether you use `margin` or `padding`. One thing which is a bit different than in regular HTML is that `width` and `height` of a container includes both margin and padding. It's just simpler and ensures that changes are backwards compatible.
Test interactive:
http://lab.concord.org/interactives-dev.html#interactives/layout-tests/borders-test.json
It won't work unless this PR is merged, but you can see new options in JSON, for example:
```
{
"id": "bottom-left",
"left": "model.left",
"top": "model.bottom",
"align": "center",
"border": "1px solid gray",
"padding": …
```

Support borders of layout containers

---

src/lab/common/controllers/export-controller.js

I think it's pretty straightforward. In some cases description is not available (iframe model), so export / logging wasn't working.

Fix a bug in export controller (triggered by missing property description)

---

src/lab/models/energy2d/models/part.js
src/lab/models/energy2d/views/parts.js

The PR is necessary to fix this model:
http://lab.concord.org/interactives.html#interactives/energy2d/htb/S5A1.json 
together with a small change to the model itself:
https://github.com/concord-consortium/lab-interactives-site/commit/73a5a1a294ded2566af391c94d169f65c70f9784
Fixed model:
http://lab.concord.org/branch/energy2d-fix/interactives.html#interactives/energy2d/htb/S5A1.json
Short description:
Each part / shape in Energy2D occupies some simulation grid cells. Those cells were calculated incorrectly, so average temperate at the edge of shape was different in Java and JS versions. That was causing incorrect radiation energy, which is based exactly on that.
There was also another issues related to floating point precision which is fixed in the S5A1.JSON itself.
This change seems …

Energy2D: fix calculation of simulation cells taken by shapes

---

src/lab/common/controllers/basic-dialog.js
src/lab/common/controllers/button-controller.js
src/lab/common/controllers/checkbox-controller.js
src/lab/common/controllers/export-controller.js
src/lab/common/controllers/help-system.js
src/lab/common/controllers/interactive-component.js
src/lab/common/controllers/interactive-metadata.js
src/lab/common/controllers/interactives-controller.js
src/lab/common/controllers/log-controller.js
src/lab/common/controllers/pulldown-controller.js
src/lab/common/controllers/radio-controller.js
src/lab/common/controllers/scripting-api.js
src/lab/common/controllers/setup-banner.js
src/lab/common/controllers/slider-controller.js
src/lab/common/lab-modeler-mixin.js
src/lab/common/playback-support.js
src/lab/import-export/dg-exporter.js
src/lab/models/iframe/modeler.js
test/mocha/common/export-controller-spec.coffee

Summary:
- There is a new `LogController` which is responsible for logging to parent window (it can be either LARA or CODAP).
- All the components log when user interacts with them (button is clicked, checkbox checked, etc.)
- All basic logs that are not specific to CODAP are extracted from `ExportsController` (e.g. "StartedModel", "ReloadedModel", "StoppedModel").
- Logging can be configured in the interactive JSON, please see [metadata spec](https://github.com/concord-consortium/lab/blob/19cc26efe39bfa4a674672fb4e20b6d7ef61446e/src/lab/common/controllers/interactive-metadata.js#L299-L316).
- Logging is enabled by default, even if you don't specify `logging` section in JSON. Then all the default values from metadata will be used, so we will log interaction with all the components and we …

Improve logging, add new event types, cleanup logging & CODAP export

---

src/lab/common/controllers/log-controller.js
src/lab/import-export/dg-exporter.js

1. Don't use RPC anymore (logging doesn't seem like a remote procedure call). 
2. Don't expect "lara-logging-present" message - parent can ignore log messages if it's not interested. 
3. Use simpler format, the same which is used by iframe-models that log to Lab:
`post("log", {action: "someAction", data: {val1: 1, val2: 2})`.
It simplifies things a lot, no setup and expectations, parent doesn't even need to use iframePhone to listen to our logs.

Simplify logging format

---

src/lab/models/md2d/views/aminoacid-context-menu.coffee

Open: http://lab.concord.org/interactives.html#interactives/samples/1-oil-and-water-shake.json
and click any atom (but don't drag it). You should notice an error in the console:
```Uncaught TypeError: Cannot read property 'abbreviation' of undefined```
This PR fixes that.

Fix console error on atom click

---

license.md
package.json
src/lab/common/controllers/setup-banner.js
src/lab/lab.build.js

If iframe doesn't specify allowfullscreen=true, we won't display fullscreen button (as it won't work anyway).

Don't display fullscreen button if fullscreen is not available

---

src/sass/lab/_interactive-components.sass

A small styles update that fixes this issue:
> If a checkbox is checked, hovering over the checkbox turns it a light-grey. This is the same state as hovering over the checkbox when it is not checked. So one can hover over the checkbox, click to check/uncheck and there is no visible change in the checkbox. Once you leave the checkbox you can see what state the box is in.

Fix checkbox hover state

---

src/lab/mml-converter/mml-converter.coffee
src/lab/models/md2d/views/images-renderer.js
test/fixtures/mml-conversions/expected-json/two-charged-atoms-with-shading-image.json
test/fixtures/mml-conversions/input-mml/two-charged-atoms-with-shading-image.mml

A small PR that fixes two issues:
- image didn't respect rotation offset value if it was attached to the radial bond
- rotation value wasn't converted from MML files

Respect image (offset) rotation when it's attached to the radial bond, convert rotation from MML

---

src/lab/mml-converter/mml-converter.coffee
src/lab/models/md2d/models/metadata.js
src/lab/models/md2d/views/images-renderer.js
src/models/chemical-reaction/chemical-reaction.json
src/models/sun-on-ground/sunOnCO2.json
src/models/sun-on-ground/sunOnGround.json
src/models/sun-on-ground/sunOnGroundAndCO2.json
test/fixtures/mml-conversions/expected-json/ellipse-alhpa-at-props.json
test/fixtures/mml-conversions/expected-json/image-layers.json
test/fixtures/mml-conversions/expected-json/image-visible-and-hidden.json
test/fixtures/mml-conversions/expected-json/sunOnGround.json
test/fixtures/mml-conversions/expected-json/target-game-distance.json
test/fixtures/mml-conversions/expected-json/two-charged-atoms-with-shading-image.json

A simple feature that makes authoring easier (we're not constrained by 1px = 0.01nm conversion anymore) and lets us support high-dpi displays.

Add "scale" property to MD2D images

---

src/lab/common/controllers/credits-dialog.js
src/lab/common/controllers/interactive-metadata.js
src/lab/common/controllers/interactives-controller.js

Adds "credits" option to the interactive JSON. Markdown is supported.

Let authors specify custom credits per interactive

---

package.json
src/lab/common/views/color.js
src/lab/models/md2d/models/engine/md2d.js
src/lab/models/md2d/models/metadata.js
src/lab/models/md2d/views/atoms-renderer.js
src/lab/models/md2d/views/bonds-renderer.js

- Atoms rendering supports alpha channel / opacity. It can be specified via color definition or "visible" property (see below).
- Atom color can be specified using typical HTML color definition, including rgba (e.g. "#ff00aa", "rgb(100,50,20)" or "rgba(10,50,20,0.5)"). Old format is still supported (magic numbers coming from Classic MW).
- Atom's "visible" property now accepts fractional values within [0, 1] range, so it can be used to control atom's opacity. The name isn't perfect, but it's backward compatible and we don't need to add another property.
- Radial bonds follow atom's opacity now. When atoms are invisible, radial bonds will be invisible too.

Color and opacity of atoms

---

src/lab/models/md2d/controllers/scripting-api.js
src/lab/models/md2d/views/dna-edit-dialog.js
src/sass/lab/_dialogs.sass

DNA dialog didn't work after the model was reset. This PR adds .bindModel method (similar methods are used in other places) and adds an original DNA sequence to the DNA dialog (Frieda requested that).

Fix DNA Dialog and add an original DNA sequence

---

src/lab/models/energy2d/metadata.js
src/lab/models/energy2d/modeler.js
src/lab/models/iframe/metadata.js
src/lab/models/iframe/modeler.js

Adds support of CODAP embedding to iframe and energy2d models.
1. If `controlButtonStyle` property is not declared in metadata, it can't be observed. CODAP was notifying Lab that it was available and the property value was updated. However, the observer wasn't being called. So, users couldn't see CODAP-specific buttons. 
2. CODAP export requires the model to define `hasPlayed` output. It's been added both to iframe and energy2d models.
[#156526419]

Adds support of CODAP embedding to iframe and energy2d models

---

src/lab/common/controllers/export-controller.js
test/mocha/common/export-controller-spec.coffee

[#157536289]
The first point of CODAP export data used to show the value that was available on the model load and/or after reset. Now, it will show the last current value before the user clicked start.

Fix the first point of the CODAP export data

---

src/lab/import-export/codap-interface.js

Having reviewed the [PT story](https://www.pivotaltracker.com/story/show/160957951) and checked the corresponding [documentation](https://github.com/concord-consortium/codap/wiki/CODAP-Data-Interactive-Plugin-API#the-interactiveframe-object) I've added the attribute to the call to the update action. I am unsure how to test whether this works as required without additional information on the CODAP use case, but I was able to compile and embed in a local CODAP instance and export data for analysis.

Allow Data Hierarchy reorg when embedded in CODAP

---

src/lab/models/md2d/controllers/scripting-api.js
src/lab/models/md2d/models/modeler.js

Since we have the ability to add and remove textboxes on the fly, this PR implements similar functionality for images. Tested against a local lab-interactives-site instance and was able to add images to newly-added particles. Seems the event for imagesChanged already exists, so I don't think there's a lot more needed here?

Add handlers for calls to add and remove an image

---

script/s3-deploy.sh

Travis was reporting build success, but buried in the logs it seems the s3 deployment piece was failing just as it was in the interactive site. Modifying the s3 deployment script was necessary to get the deployment to work.

Using a similar approach to the recent fix in lab-interactive-site

---

src/lab/models/md2d/views/genetic-anim-states.js

This will have a small change for anyone using the older version of this interactive, but it’s a relatively minor color change that shouldn't affect too many people.

Change nucleus background color to match new styles for CBio

---

src/lab/models/md2d/views/dna-edit-dialog.js

Slightly manual process to adjust the text - ideally would have changed the height of the div with css but an extra div with a non-breaking space should do the job sufficiently for one line of text in this case.

Adjust wording on popup where user is prompted to enter a DNA sequence

---

package.json
src/lab/models/md2d/views/atoms-renderer.js

iOS 13 broke rendering the gradient svg particles we use in Lab. This quick fix provides a non-gradient default image for particles that will only appear if the gradient overlay fails to render, providing a fallback option for those devices having issues rendering the SVG.
The adjustments to the stop-color style did not have an effect on the SVG, the issue could be related to our use of Pixi.js, but the issue was present also in Pixi v3. Pixi is currently on v5 but this has not yet been successfully tested with Lab.

Adjust svg rendering of atoms

---

src/lab/models/dual-sensor-connector/modeler.js
src/lab/models/sensor-connector/modeler.js

- Always try https for sensor-connector communication and then fall back to http if necessary
- Add declaration for `isNewRunInProgress` parameter
- without this, the Reset button encountered an error about modifying a readonly object
Note that in my testing the collection of sensor values and the reset button worked as expected for the single-sensor and the dual-sensor interactives, but the dual-sensor interactive would sometimes fail to complete the run, claiming that the sensor-connector could no longer be found. I'm inclined to think that's not related to the changes in this PR, however.

Fix sensor-connector interactive

---

src/sass/bourbon/functions/_deprecated-webkit-gradient.scss

Eliminates ~20 deprecation warnings of the following form:
```
DEPRECATION WARNING: Passing 100%, a non-string value, to unquote()
will be an error in future versions of Sass.
on line 30 of /Users/kswenson/Development/cc-dev/lab/src/sass/bourbon/functions/_deprecated-webkit-gradient.scss
```

Eliminate SASS deprecation warning messages
